import type { Metadata } from 'next';

import { ReactQueryProvider, StyledComponentsRegistry } from '@/libs/providers';
import { sans } from '@/libs/theme';
import '@/libs/theme/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={sans.variable} lang='fa' dir='rtl'>
      <body>
        <ReactQueryProvider>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
